services:
  - type: web
    name: gpt-to-slides
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: service_account.json
